#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory
set -x

phaseSystems/Allwmake $targetType $*
porousModels/Allwmake $targetType $*
blockSystems/Allwmake $targetType $*

compositionalDarcyFoam/Allwmake $targetType $*
compositionalRhoSwDarcyFoam/Allwmake $targetType $*
compositionalRhoSwGLSDarcyFoam/Allwmake $targetType $*
compositionalRhoGLSDarcyFoam/Allwmake $targetType $*
quaternaryRhoNsCompositionalDarcyFoam/Allwmake $targetType $*
quaternaryRhoCompositionalDarcyFoam/Allwmake $targetType $*
binaryRhoCompositionalDarcyFoam/Allwmake $targetType $*
compositionalPoreSwDarcyFoam/Allwmake $targetType $*
compositionalSwGLSDarcyFoam/Allwmake $targetType $*
compositionalSwDarcyFoam/Allwmake $targetType $*
compositionalGLSDarcyFoam/Allwmake $targetType $*
quaternaryNsCompositionalDarcyFoam/Allwmake $targetType $*
quaternaryCompositionalDarcyFoam/Allwmake $targetType $*
binaryCompositionalDarcyFoam/Allwmake $targetType $*
coupledMatrixFoam/Allwmake $targetType $*

#------------------------------------------------------------------------------
